export const GETTASKSUCCESS="GET_TASK_SUCCESS"
export const ACTIVETASK="ACTIVE_TASK"

export const GETUSERSUCCESS="GET_USER_SUCCESS"
export const ACTIVEUSER="ACTIVE_USER"

export const LOGINSTATUS="LOGIN_STATUS"

export const GETLOGINMODAL ="GET_LOGIN_MODAL"
export const GETNOTIFICATIONMODAL ="GET_NOTIFICATION_MODAL"

export const GETREGISTERMODAL ="GET_REGISTER_MODAL"

export const GETREMİNDERSUCCESS="GET_REMİNDER_SUCCESS"
export const ACTIVEREMİNDER="ACTIVE_REMİNDER"

export const GETROLESUCCESS="GET_ROLE_SUCCESS"
export const ACTIVEROLE="ACTIVE_ROLE"