# Generated by Django 4.0.3 on 2022-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='Component',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='translate',
            name='Lang',
            field=models.CharField(max_length=1200),
        ),
    ]
