# Generated by Django 4.0.4 on 2022-04-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1200)),
                ('Description', models.CharField(max_length=12000)),
                ('Priority', models.CharField(max_length=12000)),
                ('Label', models.ImageField(upload_to='product_images')),
                ('Time', models.DateTimeField()),
                ('Reminder', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.users')),
            ],
        ),
    ]
