# Generated by Django 4.0.4 on 2022-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Stat',
            field=models.CharField(default='', max_length=12000),
            preserve_default=False,
        ),
    ]
