# Generated by Django 4.0.4 on 2022-04-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RemindTime', models.DateTimeField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.tasks')),
            ],
        ),
    ]
