# Generated by Django 4.0.4 on 2022-04-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Reminders',
        ),
    ]
