# Generated by Django 4.0.4 on 2022-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_rename_tasks_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='ReminderStat',
            field=models.BooleanField(default=False),
        ),
    ]
