# Generated by Django 4.0.4 on 2022-04-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dashboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Surname', models.CharField(max_length=120)),
                ('Username', models.CharField(max_length=120)),
                ('Gender', models.CharField(max_length=120)),
                ('Birthday', models.DateField()),
                ('Phone', models.CharField(max_length=1200)),
                ('Email', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=500)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.roles')),
            ],
        ),
    ]
